### ISSUE TITLE
what is licence of this codes?

### ISSUE THREAD

**Issue by ryogrid** [brunocalza/go-bustub#1]
@brunocalza 
hi. brunocalza.
Codes of this repo are great and I want to praise your work.

Then, I want to know licence of codes on this repo.
Because, I plan writing RDB in Golang like you and I want develop it based on your codes.

I think you can apply any licence you want because this repo does not include codes of BusTub which is wrote in cpp.

regards,
ryo_grid

**Comment by brunocalza** [comment]
hey @ryogrid just added a MIT LICENSE. 

i'm glad you enjoyed the code. I haven't had time to add more features to this lately

what are you planning to build?

**Comment by ryogrid** [comment]
@brunocalza 
Thank you for your fast action!
  
I'm planning build of simple RDB which has features you listed at README.md of this repo and additional basic features :-)
I want to develop RDB for enjoy.
So my implementation will be simple one.
 
If the codes of the RDB are wrote clean, I hope it becomes reference or example code of RDB for people like me :-)
